services:

  redis:
    build:
      context: ./redis/
      dockerfile: Dockerfile
    container_name: redis
    expose:
      - "6379"
    networks:
      - redis-net
  
  base:
    build:
      context: ./backend/packages/
      dockerfile: Dockerfile.base
    image: base
    entrypoint: ["true"]


  gateway:
    build:
      context: ./backend/gateway/
      dockerfile: Dockerfile
    container_name: gateway
    env_file: ".env"
    volumes:
      - ./.certs:/etc/certs:z
    depends_on:
      - base
    ports:
      - "3000:3000"
    expose:
      - "3000"
    networks:
      - backend-net
      - redis-net
      - frontend-net

  auth-api:
    build:
      context: ./backend/auth-API/
      dockerfile: Dockerfile
    container_name: auth-API
    env_file: ".env"
    volumes:
      - auth-db:/app/data:z
      - ./.certs:/etc/certs:z
    depends_on:
      - base
      - redis
    expose:
      - "3005"
    networks:
      - backend-net
      - redis-net

  user-api:
    build:
      context: ./backend/user-API/
      dockerfile: Dockerfile
    container_name: user-API
    env_file: ".env"
    volumes:
      - user-db:/app/data:z
    depends_on:
      - base
      - gateway
    expose:
      - "3001"
    networks:
      - backend-net
      - redis-net

  upload-api:
    build:
      context: ./backend/upload-API/
      dockerfile: Dockerfile
    container_name: upload-API
    env_file: ".env"
    volumes:
      - uploads:/app/uploads:z
    depends_on:
      - base
    expose:
      - "3002"
    networks:
      - backend-net
      - redis-net

  game-api:
    build:
      context: ./backend/game-API/
      dockerfile: Dockerfile
    container_name: game-API
    env_file: ".env"
    volumes:
      - game-db:/app/data:z
    depends_on:
      - base
      - redis
    expose:
      - "3003"
    networks:
      - backend-net
      - redis-net

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: frontend
    env_file: ".env"
    depends_on:
      - gateway
    volumes:
      - ./.certs:/etc/certs:z
    ports:
      - "5173:5173"
    expose: 
      - "5173"
    networks:
      - frontend-net

volumes:
  user-db:
    driver: local
  game-db:
    driver: local
  auth-db:
    driver: local
  uploads:
    driver: local


networks:
  redis-net:
    driver: bridge
  backend-net:
    driver: bridge
  frontend-net:
    driver: bridge
