services:
  redis:
    build:
      context: ./redis/
      dockerfile: Dockerfile
    container_name: redis
    expose:
        - "6379"
    networks:
        - redis-net

  Base:
    build:
      context: ./backend/packages/
      dockerfile: Dockerfile.base
    image: base
    entrypoint: ["true"]

  gateway:
    build:
      context: ./backend/gateway/
      dockerfile: Dockerfile.dev
    container_name: gateway
    env_file:
        - ./.dev.env
    volumes:
      - ./backend/gateway/src:/app/src:z
    depends_on:
      - Base
      - redis
    ports:
      - "3000:3000"
    networks:
      - backend-net
      - redis-net
      - frontend-net

  user-api:
    build:
      context: ./backend/user-API/
      dockerfile: Dockerfile.dev
    container_name: user-API
    env_file:
        - ./.dev.env
    volumes:
      - ./backend/user-API/data:/app/data:z
      - ./backend/user-API/src:/app/src:z
    depends_on:
      - Base
      - redis
    expose:
      - "3001"
    networks:
      - backend-net
      - redis-net

  upload-api:
    build:
      context: ./backend/upload-API/
      dockerfile: Dockerfile.dev
    container_name: upload-API
    env_file:
        - ./.dev.env
    volumes:
      - ./backend/upload-API/data:/app/data:z
      - ./backend/upload-API/src:/app/src:z
    depends_on:
      - Base
      - redis
    expose:
      - "3002"
    networks:
      - backend-net
      - redis-net

  game-api:
    build:
      context: ./backend/game-API/
      dockerfile: Dockerfile.dev
    container_name: game-API
    env_file:
        - ./.dev.env
    volumes:
      - ./backend/game-API/data:/app/data:z
      - ./backend/game-API/src:/app/src:z
    depends_on:
      - redis
    expose:
      - "3003"
    networks:
      - backend-net
      - redis-net

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile.dev
    container_name: frontend
    env_file:
        - ./.dev.env
    volumes:
      - ./frontend/src:/app/src:z
      - ./frontend/public:/app/public:z
    ports:
      - "5173:5173"
    depends_on:
      - gateway
    networks:
      - frontend-net


networks:
  redis-net:
    driver: bridge
  backend-net:
    driver: bridge
  frontend-net:
    driver: bridge
