services:
  redis:
    build:
      context: ./redis/
      dockerfile: Dockerfile
    container_name: redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/var

volumes:
  redis_data:
    driver: local
    name: redis_data
    driver_opts:
      type: none
      device: ${PWD}/docker/redis/data
      o: bind
