FROM base

RUN apt-get update && apt-get install -y \
    wget \
    build-essential

WORKDIR /app

COPY package*.json ./
COPY tsconfig.json ./
COPY nodemon.json ./
COPY addExtensions.cjs ./

RUN npm install --build-from-source

CMD ["npm", "run", "dev"]
